### ISSUE TITLE
Images in markdown cells do not show up

### ISSUE THREAD

**Issue by gretzteam** [Valassis-Digital-Media/nbconflux#17]
Hi,
Images included part of a markdown cell are not showing up in Confluence. 
`![alt text](images/someImage.png)
`
I modified the notebook to include images like this, but it's slightly clumsy as a new cell has to be inserted just for the image...
```
from IPython.display import Image
Image("images/someImage.png")
```

**Comment by parente** [comment]
Hi @gretzteam. Markdown images are a known issue. The Confluence data format uses custom image tags, not the standard `<img>` which the markdown parser used by nbconvert produces (https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html#ConfluenceStorageFormat-Images). 

It may be possible to customize the markdown2html functionality in nbconvert. I haven't taken the time to explore it. I'm happy to take a pull request or see findings reported in comments if someone does poke around with it.

**Comment by xiangpeng2008** [comment]
Have same issue, the images rendered using base64.b64encode and HTML don't show up neither.
