### ISSUE TITLE
Add documentation for using API Token

### ISSUE THREAD

**Issue by krake-r** [Valassis-Digital-Media/nbconflux#19]
It is also possible to sign in with an Atlassian API Token for those scenarios where your organisation has employed multi-factor authentication as per: [Use an API token](https://confluence.atlassian.com/cloud/api-tokens-938839638.html)

Sign into [](https://id.atlasssian.com) with your  account. Under Security go to API Tokens then Create API Token. Give the token a meaningful label so that access can be revoked later. The token will be copied to the clipboard. Using Jupyter file editor create the token in the Jupyter environment and name the file `confluence.token`.

The api key can be used by setting the environment variables:
```
CONFLUENCE_PASSWORD=$(cat confluence.token)
CONFLUENCE_USERNAME=<me>
CONFLUENCE_URL=$(cat confluence.url)

```
Then calling `nbconflux <notebook>.ipynb $CONFLUENCE_URL`. 

Using `CONFLUENCE_URL'  was only to get around the paste to jupyter issue.

**Comment by ericdill** [comment]
Thanks Rick. 

@parente any thoughts on where to put this in the docs?

**Comment by parente** [comment]
It could go in the FAQ under "What if my organization has Two-Factor Auth configured?" Or it get mixed into the Usage section if it's clear when you need a token vs can just use your password.
