### ISSUE TITLE
Remove code cells

### ISSUE THREAD

**Issue by tvandenzegel** [Valassis-Digital-Media/nbconflux#24]
Hi All,

Is there a way to hide/remove the code cells?
So that I only see the markdown cells and the output of the code cells?

**Comment by parente** [comment]
> Excludes input, output, or entire cells based on notebook cell tags noinput, nooutput, or nocell

The README could be clearer on this topic for sure. You can use cell tags with those names to exclude the cell input, cell output, or entire cell on a per cell basis.

**Comment by tvandenzegel** [comment]
Oh I feel stupid now! 
I didn't get the tag thing before when reading it.
It works perfectly! 
Thank you very much for the fast response and for the very nice tool you made!

**Comment by parente** [comment]
@tvandenzegel Not a problem. If you have time to spare, I'd welcome a pull request with edits to the README to clarify the tagging support.
