### ISSUE TITLE
Win7/MingW64: Command prompt stuck at "Confluence username"

### ISSUE THREAD

**Issue by Sieboldianus** [Valassis-Digital-Media/nbconflux#25]
After running 

    nbconflux my_jupyter_nb.ipynb https://confluence_sample.org/page/viewpage.action?pageId=736763

.. the command prompt doesn't react to any input after request of "Confluence username:", I can't even abort using CTRL+C. Is this a known issue?

Just noticed: does this package only work with confluence hosted on atlassian.com?

I also tested this from a python-script with import: same problem - no response after "python convert.py"

**Comment by parente** [comment]
I haven't heard anyone report this behavior before, though most users I know are using the `.nbconflux` file approach to store credentials. Can you share what operating system you're on and the output of `pip list` or `conda list` if you're using either one so I can see what library versions you have installed?

> Just noticed: does this package only work with confluence hosted on atlassian.com?

It works with Confluence Server (on-premise) and Confluence Cloud. The last bullet in the features list is meant to convey this info:

> Compatible with Confluence Cloud and Confluence Server

Happy to take a pull request making it clearer if you have a suggestion.

**Comment by Sieboldianus** [comment]
Ha - that helped! I am on Windows 7 and using the Git Console (MingW64). I tried with command line and it works. Not sure what is causing the issue with MingW64..

**Comment by parente** [comment]
The code is using Python built in and standard library calls to collect username and password:

https://github.com/Valassis-Digital-Media/nbconflux/blob/master/nbconflux/cli.py#L47,L52

There must be some bad interaction between MingW64 and Python.

**Comment by Sieboldianus** [comment]
Yes, I agree and this probably has nothing to do with nbconflux. I think this issue can be closed.
